---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: week5
spec:
  encryptedData:
    API_KEY: AgCIrgULhfxmRgxZl60emRy4GZhFipglVQV3DG84jyw634XYdISKRZHi1ioJKQQUL2No8vYcSx5AJJZJBe5mkV4szddp4dcZ6TeRXI36+pDDdZMYsfdH6wBiMfAfxu0xnYvY8fz26kbfBaO5gK868x3dcakOO/Z5OfxaU0U4/LqmdDI9vrTGOMQoc3/8DZNnKlBGuogk5aqIWTt75gfd4aEjQNyIuxw1/pjYHxjojozjVJ2iBAtFRoBUQDOWpEERq1IfKeCaVyZ1haYo/KXl0d6TluZAIETC46/IEpyAjKxOCwiGbhKzXdBR5ob8Hzel+929pieQmjwG3a0INu0DjIWW3CpVdWA9K23ZDwMjGGaeubRAJW0oZzYMsUgiaq0K+jXKzzCCdRmWYpSfAdcn6NvOWR8gNxAM9cKzd8uchGdWcVrVltSFPccvL7btdGR/5zxWQzCCQGWptKEOoO90Sq1mPN6OQYIPtn7ra4JeqqLxU6Jf5rLx9L2jUrILrv9ZYzz724xt3Qq4IbwrbfKc4btiIJwWswdTygiYqaVd7CWVThN2PysATKNtml4/tYALO6y0J7z4sTBzSpaSIcogfNfTIBTQJrZmaj8ShFjVXv+WojX4Pdpi+qjh7qn1rx8wQX5ZG61I9mQA2IGg7Ipdr19tPYMUqnSBqXpVKgkdh8/HYkvJFNJKL2QrY3BAitXTJyBk+V447d1JrcpwkmB52OtsGbI=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: week5
