apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    isDefault: true
    jsonData:
      # Day 4 will use this to jump trace <-> logs; harmless now.
      maxLines: 1000

  - name: Mimir
    type: prometheus
    access: proxy
    uid: mimir
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
      prometheusType: Mimir

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    jsonData:
      # Day 4 will add tracesToLogs / tracesToMetrics correlation here.
      httpMethod: GET
